fixed text.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -20,6 +20,18 @@ jobs:
 
     - name: Install system dependencies
       run: |
+        max_attempts=5
+        attempt=1
+        until sudo apt-get update; do
+        if [ $attempt -ge $max_attempts ]; then
+         echo "apt-get update failed after $max_attempts attempts."
+         exit 1
+        fi
+        echo "Apt lock is held, retrying in 5 seconds... (attempt $attempt/$max_attempts)"
+        attempt=$((attempt+1))
+        sleep 5
+        done
+        
         sudo apt-get update
         sudo apt-get install -y libcairo2-dev pkg-config python3-dev
 
